-- Logistics ERP MySQL 8 schema
-- Scope: multi-company dispatch/logistics ERP with accounting, fleet, HR, compliance,
-- inventory, documents, GPS, fuel, orders, trips, and settlement workflows.

CREATE DATABASE IF NOT EXISTS logistics_erp
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE logistics_erp;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS currencies (
  currency_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code CHAR(3) NOT NULL,
  name VARCHAR(80) NOT NULL,
  symbol VARCHAR(10) NULL,
  decimal_places TINYINT UNSIGNED NOT NULL DEFAULT 2,
  is_base_default BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (currency_id),
  UNIQUE KEY uk_currencies_code (code),
  KEY idx_currencies_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS companies (
  company_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  parent_company_id BIGINT UNSIGNED NULL,
  legal_name VARCHAR(180) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  tax_number VARCHAR(80) NULL,
  base_currency_id BIGINT UNSIGNED NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
  fiscal_year_start_month TINYINT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('ACTIVE','INACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (company_id),
  UNIQUE KEY uk_companies_legal_name (legal_name),
  UNIQUE KEY uk_companies_tax_number (tax_number),
  KEY idx_companies_parent (parent_company_id),
  KEY idx_companies_currency (base_currency_id),
  KEY idx_companies_status (status),
  CONSTRAINT fk_companies_parent FOREIGN KEY (parent_company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_companies_currency FOREIGN KEY (base_currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_settings (
  company_setting_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  setting_key VARCHAR(120) NOT NULL,
  setting_value JSON NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (company_setting_id),
  UNIQUE KEY uk_company_settings_key (company_id, setting_key),
  KEY idx_company_settings_status (status),
  CONSTRAINT fk_company_settings_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_currency_rates (
  rate_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  base_currency_id BIGINT UNSIGNED NOT NULL,
  quote_currency_id BIGINT UNSIGNED NOT NULL,
  rate_date DATE NOT NULL,
  rate DECIMAL(18,8) NOT NULL,
  source ENUM('MANUAL','OPEN_EXCHANGE','ECB','BANK','OTHER_API') NOT NULL DEFAULT 'MANUAL',
  status ENUM('ACTIVE','SUPERSEDED','FAILED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (rate_id),
  UNIQUE KEY uk_daily_currency_rates (company_id, base_currency_id, quote_currency_id, rate_date),
  KEY idx_daily_currency_rates_date (rate_date),
  KEY idx_daily_currency_rates_status (status),
  CONSTRAINT fk_daily_rates_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_daily_rates_base_currency FOREIGN KEY (base_currency_id) REFERENCES currencies(currency_id),
  CONSTRAINT fk_daily_rates_quote_currency FOREIGN KEY (quote_currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS financial_years (
  financial_year_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  year_code VARCHAR(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_closed BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('OPEN','LOCKED','CLOSED') NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (financial_year_id),
  UNIQUE KEY uk_financial_years_company_code (company_id, year_code),
  KEY idx_financial_years_dates (start_date, end_date),
  KEY idx_financial_years_status (status),
  CONSTRAINT fk_financial_years_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS terminals (
  terminal_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  terminal_code VARCHAR(30) NOT NULL,
  name VARCHAR(140) NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
  address_line1 VARCHAR(180) NOT NULL,
  address_line2 VARCHAR(180) NULL,
  city VARCHAR(80) NOT NULL,
  state_region VARCHAR(80) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country_code CHAR(2) NOT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (terminal_id),
  UNIQUE KEY uk_terminals_company_code (company_id, terminal_code),
  KEY idx_terminals_company_status (company_id, status),
  KEY idx_terminals_geo (latitude, longitude),
  CONSTRAINT fk_terminals_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS warehouses (
  warehouse_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  terminal_id BIGINT UNSIGNED NULL,
  warehouse_code VARCHAR(30) NOT NULL,
  name VARCHAR(140) NOT NULL,
  warehouse_type ENUM('GENERAL','CROSS_DOCK','COLD_STORAGE','PARTS','YARD') NOT NULL DEFAULT 'GENERAL',
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (warehouse_id),
  UNIQUE KEY uk_warehouses_company_code (company_id, warehouse_code),
  KEY idx_warehouses_terminal (terminal_id),
  KEY idx_warehouses_type_status (warehouse_type, status),
  CONSTRAINT fk_warehouses_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_warehouses_terminal FOREIGN KEY (terminal_id) REFERENCES terminals(terminal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS roles (
  role_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NULL,
  role_code VARCHAR(50) NOT NULL,
  role_name VARCHAR(120) NOT NULL,
  description VARCHAR(255) NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (role_id),
  UNIQUE KEY uk_roles_company_code (company_id, role_code),
  KEY idx_roles_status (status),
  CONSTRAINT fk_roles_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS permissions (
  permission_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  permission_key VARCHAR(120) NOT NULL,
  module_name VARCHAR(80) NOT NULL,
  action_name VARCHAR(80) NOT NULL,
  description VARCHAR(255) NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (permission_id),
  UNIQUE KEY uk_permissions_key (permission_key),
  KEY idx_permissions_module_action (module_name, action_name),
  KEY idx_permissions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS role_permissions (
  role_permission_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  role_id BIGINT UNSIGNED NOT NULL,
  permission_id BIGINT UNSIGNED NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (role_permission_id),
  UNIQUE KEY uk_role_permissions (role_id, permission_id),
  KEY idx_role_permissions_permission (permission_id),
  KEY idx_role_permissions_status (status),
  CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(role_id),
  CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS designations (
  designation_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  designation_code VARCHAR(40) NOT NULL,
  designation_name VARCHAR(120) NOT NULL,
  department VARCHAR(80) NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (designation_id),
  UNIQUE KEY uk_designations_company_code (company_id, designation_code),
  KEY idx_designations_department (department),
  KEY idx_designations_status (status),
  CONSTRAINT fk_designations_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employees (
  employee_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  employee_code VARCHAR(40) NOT NULL,
  designation_id BIGINT UNSIGNED NULL,
  home_terminal_id BIGINT UNSIGNED NULL,
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  email VARCHAR(160) NULL,
  phone VARCHAR(40) NULL,
  hire_date DATE NULL,
  employment_type ENUM('FULL_TIME','PART_TIME','CONTRACT','TEMPORARY') NOT NULL DEFAULT 'FULL_TIME',
  status ENUM('ACTIVE','ON_LEAVE','TERMINATED','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (employee_id),
  UNIQUE KEY uk_employees_company_code (company_id, employee_code),
  UNIQUE KEY uk_employees_email (email),
  KEY idx_employees_designation (designation_id),
  KEY idx_employees_terminal (home_terminal_id),
  KEY idx_employees_status (company_id, status),
  CONSTRAINT fk_employees_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_employees_designation FOREIGN KEY (designation_id) REFERENCES designations(designation_id),
  CONSTRAINT fk_employees_terminal FOREIGN KEY (home_terminal_id) REFERENCES terminals(terminal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  employee_id BIGINT UNSIGNED NULL,
  username VARCHAR(80) NOT NULL,
  email VARCHAR(160) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  last_login_at TIMESTAMP NULL,
  status ENUM('ACTIVE','LOCKED','INVITED','DISABLED') NOT NULL DEFAULT 'INVITED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  UNIQUE KEY uk_users_username (username),
  UNIQUE KEY uk_users_email (email),
  KEY idx_users_company_status (company_id, status),
  KEY idx_users_employee (employee_id),
  CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_users_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_roles (
  user_role_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  company_id BIGINT UNSIGNED NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_role_id),
  UNIQUE KEY uk_user_roles (user_id, role_id, company_id),
  KEY idx_user_roles_role (role_id),
  KEY idx_user_roles_company_status (company_id, status),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(user_id),
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(role_id),
  CONSTRAINT fk_user_roles_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS menus (
  menu_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NULL,
  parent_menu_id BIGINT UNSIGNED NULL,
  permission_id BIGINT UNSIGNED NULL,
  menu_code VARCHAR(80) NOT NULL,
  menu_label VARCHAR(120) NOT NULL,
  menu_type ENUM('MODULE','PAGE','OPTION','ACTION') NOT NULL DEFAULT 'PAGE',
  route_path VARCHAR(180) NULL,
  icon_name VARCHAR(80) NULL,
  display_order INT NOT NULL DEFAULT 0,
  is_visible BOOLEAN NOT NULL DEFAULT TRUE,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (menu_id),
  UNIQUE KEY uk_menus_company_code (company_id, menu_code),
  KEY idx_menus_parent_order (parent_menu_id, display_order),
  KEY idx_menus_permission (permission_id),
  KEY idx_menus_visible_status (is_visible, status),
  CONSTRAINT fk_menus_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_menus_parent FOREIGN KEY (parent_menu_id) REFERENCES menus(menu_id),
  CONSTRAINT fk_menus_permission FOREIGN KEY (permission_id) REFERENCES permissions(permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS party_groups (
  party_group_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  group_code VARCHAR(40) NOT NULL,
  group_name VARCHAR(120) NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (party_group_id),
  UNIQUE KEY uk_party_groups_company_code (company_id, group_code),
  KEY idx_party_groups_status (status),
  CONSTRAINT fk_party_groups_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS parties (
  party_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  party_group_id BIGINT UNSIGNED NULL,
  party_code VARCHAR(50) NOT NULL,
  party_name VARCHAR(180) NOT NULL,
  party_type ENUM('CUSTOMER','SHIPPER','RECEIVER','SUPPLIER','CARRIER','BROKER','OTHER') NOT NULL,
  tax_number VARCHAR(80) NULL,
  credit_limit DECIMAL(16,2) NOT NULL DEFAULT 0.00,
  payment_terms_days SMALLINT UNSIGNED NOT NULL DEFAULT 30,
  default_currency_id BIGINT UNSIGNED NOT NULL,
  account_status ENUM('ACTIVE','HOLD','INACTIVE','BLACKLISTED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (party_id),
  UNIQUE KEY uk_parties_company_code (company_id, party_code),
  KEY idx_parties_type_status (party_type, account_status),
  KEY idx_parties_group (party_group_id),
  KEY idx_parties_currency (default_currency_id),
  CONSTRAINT fk_parties_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_parties_group FOREIGN KEY (party_group_id) REFERENCES party_groups(party_group_id),
  CONSTRAINT fk_parties_currency FOREIGN KEY (default_currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS party_contacts (
  party_contact_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  party_id BIGINT UNSIGNED NOT NULL,
  contact_name VARCHAR(120) NOT NULL,
  title VARCHAR(80) NULL,
  email VARCHAR(160) NULL,
  phone VARCHAR(40) NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (party_contact_id),
  KEY idx_party_contacts_party_primary (party_id, is_primary),
  KEY idx_party_contacts_email (email),
  KEY idx_party_contacts_status (status),
  CONSTRAINT fk_party_contacts_party FOREIGN KEY (party_id) REFERENCES parties(party_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS party_addresses (
  party_address_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  party_id BIGINT UNSIGNED NOT NULL,
  address_type ENUM('BILLING','SHIPPING','PICKUP','DELIVERY','YARD','OTHER') NOT NULL DEFAULT 'SHIPPING',
  address_line1 VARCHAR(180) NOT NULL,
  address_line2 VARCHAR(180) NULL,
  city VARCHAR(80) NOT NULL,
  state_region VARCHAR(80) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country_code CHAR(2) NOT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (party_address_id),
  KEY idx_party_addresses_party_type (party_id, address_type),
  KEY idx_party_addresses_city_state (city, state_region),
  KEY idx_party_addresses_geo (latitude, longitude),
  CONSTRAINT fk_party_addresses_party FOREIGN KEY (party_id) REFERENCES parties(party_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS predefined_addresses (
  predefined_address_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  address_code VARCHAR(50) NOT NULL,
  name VARCHAR(140) NOT NULL,
  address_line1 VARCHAR(180) NOT NULL,
  address_line2 VARCHAR(180) NULL,
  city VARCHAR(80) NOT NULL,
  state_region VARCHAR(80) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country_code CHAR(2) NOT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (predefined_address_id),
  UNIQUE KEY uk_predefined_addresses_company_code (company_id, address_code),
  KEY idx_predefined_addresses_city_state (city, state_region),
  KEY idx_predefined_addresses_status (status),
  CONSTRAINT fk_predefined_addresses_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS address_lanes (
  address_lane_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  from_address_id BIGINT UNSIGNED NOT NULL,
  to_address_id BIGINT UNSIGNED NOT NULL,
  distance_miles DECIMAL(10,2) NOT NULL,
  expected_duration_minutes INT UNSIGNED NOT NULL,
  toll_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (address_lane_id),
  UNIQUE KEY uk_address_lanes_pair (company_id, from_address_id, to_address_id),
  KEY idx_address_lanes_from (from_address_id),
  KEY idx_address_lanes_to (to_address_id),
  KEY idx_address_lanes_distance (distance_miles),
  CONSTRAINT fk_address_lanes_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_address_lanes_from FOREIGN KEY (from_address_id) REFERENCES predefined_addresses(predefined_address_id),
  CONSTRAINT fk_address_lanes_to FOREIGN KEY (to_address_id) REFERENCES predefined_addresses(predefined_address_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chart_of_accounts (
  account_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  parent_account_id BIGINT UNSIGNED NULL,
  account_code VARCHAR(40) NOT NULL,
  account_name VARCHAR(140) NOT NULL,
  account_type ENUM('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE') NOT NULL,
  normal_balance ENUM('DEBIT','CREDIT') NOT NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (account_id),
  UNIQUE KEY uk_chart_accounts_company_code (company_id, account_code),
  KEY idx_chart_accounts_parent (parent_account_id),
  KEY idx_chart_accounts_type_status (account_type, status),
  KEY idx_chart_accounts_currency (currency_id),
  CONSTRAINT fk_chart_accounts_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_chart_accounts_parent FOREIGN KEY (parent_account_id) REFERENCES chart_of_accounts(account_id),
  CONSTRAINT fk_chart_accounts_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS party_accounts (
  party_account_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  party_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  account_role ENUM('AR','AP','BOTH') NOT NULL DEFAULT 'BOTH',
  status ENUM('ACTIVE','ON_HOLD','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (party_account_id),
  UNIQUE KEY uk_party_accounts (party_id, account_role),
  KEY idx_party_accounts_company_status (company_id, status),
  KEY idx_party_accounts_account (account_id),
  CONSTRAINT fk_party_accounts_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_party_accounts_party FOREIGN KEY (party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_party_accounts_account FOREIGN KEY (account_id) REFERENCES chart_of_accounts(account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS drivers (
  driver_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  employee_id BIGINT UNSIGNED NULL,
  driver_code VARCHAR(40) NOT NULL,
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  phone VARCHAR(40) NULL,
  email VARCHAR(160) NULL,
  license_number VARCHAR(80) NOT NULL,
  license_state VARCHAR(40) NOT NULL,
  license_expiry_date DATE NOT NULL,
  driver_type ENUM('COMPANY','OWNER_OPERATOR','CONTRACTOR') NOT NULL DEFAULT 'COMPANY',
  pay_type ENUM('MILE','HOURLY','PERCENTAGE','FLAT') NOT NULL DEFAULT 'MILE',
  status ENUM('ACTIVE','ON_LEAVE','SUSPENDED','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (driver_id),
  UNIQUE KEY uk_drivers_company_code (company_id, driver_code),
  UNIQUE KEY uk_drivers_license (license_number, license_state),
  KEY idx_drivers_employee (employee_id),
  KEY idx_drivers_status (company_id, status),
  CONSTRAINT fk_drivers_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_drivers_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trucks (
  truck_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  terminal_id BIGINT UNSIGNED NULL,
  truck_number VARCHAR(40) NOT NULL,
  vin VARCHAR(80) NOT NULL,
  plate_number VARCHAR(40) NOT NULL,
  make VARCHAR(80) NULL,
  model VARCHAR(80) NULL,
  model_year SMALLINT UNSIGNED NULL,
  ownership_type ENUM('COMPANY','LEASED','OWNER_OPERATOR') NOT NULL DEFAULT 'COMPANY',
  current_odometer_miles DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('AVAILABLE','DISPATCHED','MAINTENANCE','OUT_OF_SERVICE','INACTIVE') NOT NULL DEFAULT 'AVAILABLE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (truck_id),
  UNIQUE KEY uk_trucks_company_number (company_id, truck_number),
  UNIQUE KEY uk_trucks_vin (vin),
  KEY idx_trucks_terminal (terminal_id),
  KEY idx_trucks_status (company_id, status),
  CONSTRAINT fk_trucks_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_trucks_terminal FOREIGN KEY (terminal_id) REFERENCES terminals(terminal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trailer_assets (
  trailer_asset_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  terminal_id BIGINT UNSIGNED NULL,
  asset_number VARCHAR(40) NOT NULL,
  asset_type ENUM('TRAILER','CONTAINER','CHASSIS') NOT NULL,
  vin_or_serial VARCHAR(80) NOT NULL,
  plate_number VARCHAR(40) NULL,
  length_feet DECIMAL(8,2) NULL,
  max_weight_lbs DECIMAL(12,2) NULL,
  container_load_status ENUM('EMPTY','LOADED','UNKNOWN') NULL,
  ownership_type ENUM('COMPANY','LEASED','CUSTOMER','CARRIER') NOT NULL DEFAULT 'COMPANY',
  status ENUM('AVAILABLE','DISPATCHED','MAINTENANCE','OUT_OF_SERVICE','INACTIVE') NOT NULL DEFAULT 'AVAILABLE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trailer_asset_id),
  UNIQUE KEY uk_trailer_assets_company_number (company_id, asset_number),
  UNIQUE KEY uk_trailer_assets_serial (vin_or_serial),
  KEY idx_trailer_assets_type_status (asset_type, status),
  KEY idx_trailer_assets_terminal (terminal_id),
  CONSTRAINT fk_trailer_assets_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_trailer_assets_terminal FOREIGN KEY (terminal_id) REFERENCES terminals(terminal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fuel_cards (
  fuel_card_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  provider_name VARCHAR(120) NOT NULL,
  card_number_masked VARCHAR(40) NOT NULL,
  external_card_id VARCHAR(100) NULL,
  status ENUM('ACTIVE','SUSPENDED','CANCELLED','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  issued_at DATE NULL,
  expires_at DATE NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (fuel_card_id),
  UNIQUE KEY uk_fuel_cards_company_masked (company_id, card_number_masked),
  KEY idx_fuel_cards_provider (provider_name),
  KEY idx_fuel_cards_status (status),
  CONSTRAINT fk_fuel_cards_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS truck_fuel_card_assignments (
  assignment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  truck_id BIGINT UNSIGNED NOT NULL,
  fuel_card_id BIGINT UNSIGNED NOT NULL,
  assigned_at DATETIME NOT NULL,
  unassigned_at DATETIME NULL,
  status ENUM('ACTIVE','ENDED','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (assignment_id),
  UNIQUE KEY uk_truck_fuel_card_active (truck_id, fuel_card_id, assigned_at),
  KEY idx_truck_fuel_assignments_card (fuel_card_id),
  KEY idx_truck_fuel_assignments_status (status),
  CONSTRAINT fk_truck_fuel_assignments_truck FOREIGN KEY (truck_id) REFERENCES trucks(truck_id),
  CONSTRAINT fk_truck_fuel_assignments_card FOREIGN KEY (fuel_card_id) REFERENCES fuel_cards(fuel_card_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fuel_upload_batches (
  fuel_upload_batch_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  source ENUM('EXCEL','BDE_API','MANUAL','OTHER_API') NOT NULL,
  source_file_name VARCHAR(180) NULL,
  external_batch_id VARCHAR(100) NULL,
  uploaded_by_user_id BIGINT UNSIGNED NULL,
  uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('PENDING','PROCESSING','COMPLETED','FAILED','PARTIAL') NOT NULL DEFAULT 'PENDING',
  error_message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (fuel_upload_batch_id),
  UNIQUE KEY uk_fuel_upload_batches_external (company_id, external_batch_id),
  KEY idx_fuel_upload_batches_company_status (company_id, status),
  KEY idx_fuel_upload_batches_user (uploaded_by_user_id),
  CONSTRAINT fk_fuel_upload_batches_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_fuel_upload_batches_user FOREIGN KEY (uploaded_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fuel_transactions (
  fuel_transaction_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  fuel_upload_batch_id BIGINT UNSIGNED NULL,
  truck_id BIGINT UNSIGNED NULL,
  driver_id BIGINT UNSIGNED NULL,
  fuel_card_id BIGINT UNSIGNED NULL,
  transaction_at DATETIME NOT NULL,
  vendor_name VARCHAR(160) NOT NULL,
  city VARCHAR(80) NULL,
  state_region VARCHAR(80) NULL,
  gallons DECIMAL(12,3) NOT NULL,
  price_per_gallon DECIMAL(12,4) NOT NULL,
  total_amount DECIMAL(14,2) NOT NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  odometer_miles DECIMAL(12,2) NULL,
  external_transaction_id VARCHAR(120) NULL,
  status ENUM('IMPORTED','MATCHED','DISPUTED','VOID') NOT NULL DEFAULT 'IMPORTED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (fuel_transaction_id),
  UNIQUE KEY uk_fuel_transactions_external (company_id, external_transaction_id),
  KEY idx_fuel_transactions_truck_date (truck_id, transaction_at),
  KEY idx_fuel_transactions_driver_date (driver_id, transaction_at),
  KEY idx_fuel_transactions_batch (fuel_upload_batch_id),
  KEY idx_fuel_transactions_status (status),
  CONSTRAINT fk_fuel_transactions_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_fuel_transactions_batch FOREIGN KEY (fuel_upload_batch_id) REFERENCES fuel_upload_batches(fuel_upload_batch_id),
  CONSTRAINT fk_fuel_transactions_truck FOREIGN KEY (truck_id) REFERENCES trucks(truck_id),
  CONSTRAINT fk_fuel_transactions_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id),
  CONSTRAINT fk_fuel_transactions_card FOREIGN KEY (fuel_card_id) REFERENCES fuel_cards(fuel_card_id),
  CONSTRAINT fk_fuel_transactions_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gps_devices (
  gps_device_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  device_imei VARCHAR(80) NOT NULL,
  provider_name VARCHAR(120) NOT NULL,
  entity_type ENUM('TRUCK','TRAILER','CONTAINER','CHASSIS','DRIVER') NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  timezone VARCHAR(20) NOT NULL DEFAULT 'UTC',
  status ENUM('ACTIVE','INACTIVE','LOST','RETIRED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (gps_device_id),
  UNIQUE KEY uk_gps_devices_imei (device_imei),
  KEY idx_gps_devices_entity (entity_type, entity_id),
  KEY idx_gps_devices_company_status (company_id, status),
  CONSTRAINT fk_gps_devices_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gps_positions (
  gps_position_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  gps_device_id BIGINT UNSIGNED NOT NULL,
  recorded_at_utc TIMESTAMP NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  speed_mph DECIMAL(8,2) NULL,
  heading_degrees SMALLINT UNSIGNED NULL,
  odometer_miles DECIMAL(12,2) NULL,
  engine_hours DECIMAL(12,2) NULL,
  raw_payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (gps_position_id),
  KEY idx_gps_positions_device_time (gps_device_id, recorded_at_utc),
  KEY idx_gps_positions_geo (latitude, longitude),
  CONSTRAINT fk_gps_positions_device FOREIGN KEY (gps_device_id) REFERENCES gps_devices(gps_device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS document_types (
  document_type_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NULL,
  document_type_code VARCHAR(60) NOT NULL,
  document_type_name VARCHAR(140) NOT NULL,
  applies_to_entity VARCHAR(80) NOT NULL,
  requires_expiry_date BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (document_type_id),
  UNIQUE KEY uk_document_types_company_code (company_id, document_type_code),
  KEY idx_document_types_entity (applies_to_entity),
  KEY idx_document_types_status (status),
  CONSTRAINT fk_document_types_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS document_attachments (
  document_attachment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  document_type_id BIGINT UNSIGNED NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  file_name VARCHAR(180) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(120) NULL,
  file_size_bytes BIGINT UNSIGNED NULL,
  issue_date DATE NULL,
  expiry_date DATE NULL,
  verification_status ENUM('PENDING','VERIFIED','REJECTED','EXPIRED') NOT NULL DEFAULT 'PENDING',
  uploaded_by_user_id BIGINT UNSIGNED NULL,
  uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (document_attachment_id),
  KEY idx_document_attachments_entity (entity_type, entity_id),
  KEY idx_document_attachments_type (document_type_id),
  KEY idx_document_attachments_company_status (company_id, verification_status),
  KEY idx_document_attachments_expiry (expiry_date),
  KEY idx_document_attachments_user (uploaded_by_user_id),
  CONSTRAINT fk_document_attachments_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_document_attachments_type FOREIGN KEY (document_type_id) REFERENCES document_types(document_type_id),
  CONSTRAINT fk_document_attachments_user FOREIGN KEY (uploaded_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS driver_pay_schedules (
  driver_pay_schedule_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  driver_id BIGINT UNSIGNED NOT NULL,
  pay_frequency ENUM('WEEKLY','BIWEEKLY','SEMIMONTHLY','MONTHLY') NOT NULL DEFAULT 'WEEKLY',
  rate_type ENUM('MILE','HOUR','PERCENTAGE','FLAT') NOT NULL,
  base_rate DECIMAL(12,4) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (driver_pay_schedule_id),
  KEY idx_driver_pay_schedules_driver_dates (driver_id, effective_from, effective_to),
  KEY idx_driver_pay_schedules_company_status (company_id, status),
  CONSTRAINT fk_driver_pay_schedules_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_driver_pay_schedules_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employee_pay_schedules (
  employee_pay_schedule_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  employee_id BIGINT UNSIGNED NOT NULL,
  pay_frequency ENUM('WEEKLY','BIWEEKLY','SEMIMONTHLY','MONTHLY') NOT NULL DEFAULT 'BIWEEKLY',
  salary_type ENUM('SALARY','HOURLY') NOT NULL,
  rate_amount DECIMAL(12,4) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (employee_pay_schedule_id),
  KEY idx_employee_pay_schedules_employee_dates (employee_id, effective_from, effective_to),
  KEY idx_employee_pay_schedules_company_status (company_id, status),
  CONSTRAINT fk_employee_pay_schedules_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_employee_pay_schedules_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS carrier_pay_schedules (
  carrier_pay_schedule_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  carrier_party_id BIGINT UNSIGNED NOT NULL,
  pay_frequency ENUM('WEEKLY','BIWEEKLY','SEMIMONTHLY','MONTHLY','ON_DEMAND') NOT NULL DEFAULT 'WEEKLY',
  rate_type ENUM('MILE','PERCENTAGE','FLAT','CONTRACT') NOT NULL,
  base_rate DECIMAL(12,4) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (carrier_pay_schedule_id),
  KEY idx_carrier_pay_schedules_carrier_dates (carrier_party_id, effective_from, effective_to),
  KEY idx_carrier_pay_schedules_company_status (company_id, status),
  CONSTRAINT fk_carrier_pay_schedules_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_carrier_pay_schedules_party FOREIGN KEY (carrier_party_id) REFERENCES parties(party_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS equipment_compliance_records (
  equipment_compliance_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  equipment_type ENUM('TRUCK','TRAILER','CONTAINER','CHASSIS') NOT NULL,
  equipment_id BIGINT UNSIGNED NOT NULL,
  compliance_type ENUM('REGISTRATION','INSURANCE','ANNUAL_INSPECTION','PERMIT','MAINTENANCE','PTI') NOT NULL,
  reference_number VARCHAR(100) NULL,
  issue_date DATE NULL,
  expiry_date DATE NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('VALID','EXPIRING','EXPIRED','REJECTED','PENDING') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (equipment_compliance_id),
  KEY idx_equipment_compliance_entity (equipment_type, equipment_id),
  KEY idx_equipment_compliance_expiry (expiry_date),
  KEY idx_equipment_compliance_status (company_id, status),
  CONSTRAINT fk_equipment_compliance_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS driver_compliance_records (
  driver_compliance_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  driver_id BIGINT UNSIGNED NOT NULL,
  compliance_type ENUM('LICENSE','MEDICAL','BACKGROUND_CHECK','DRUG_TEST','TRAINING','HOS') NOT NULL,
  reference_number VARCHAR(100) NULL,
  issue_date DATE NULL,
  expiry_date DATE NULL,
  status ENUM('VALID','EXPIRING','EXPIRED','REJECTED','PENDING') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (driver_compliance_id),
  KEY idx_driver_compliance_driver_expiry (driver_id, expiry_date),
  KEY idx_driver_compliance_status (company_id, status),
  CONSTRAINT fk_driver_compliance_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_driver_compliance_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  order_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  order_number VARCHAR(50) NOT NULL,
  customer_party_id BIGINT UNSIGNED NOT NULL,
  shipper_party_id BIGINT UNSIGNED NULL,
  receiver_party_id BIGINT UNSIGNED NULL,
  freight_type ENUM('FTL','LTL','PARTIAL','INTERMODAL') NOT NULL DEFAULT 'FTL',
  temperature_requirement VARCHAR(80) NULL,
  special_conditions TEXT NULL,
  packing_support TEXT NULL,
  total_weight_lbs DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_volume_cuft DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  requested_pickup_at DATETIME NULL,
  requested_delivery_at DATETIME NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  status ENUM('DRAFT','VALIDATING','READY','PLANNED','IN_TRANSIT','PARTIAL_DELIVERED','DELIVERED','RETURNED','DESTROYED','CANCELLED','CLOSED') NOT NULL DEFAULT 'DRAFT',
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (order_id),
  UNIQUE KEY uk_orders_company_number (company_id, order_number),
  KEY idx_orders_customer_status (customer_party_id, status),
  KEY idx_orders_dates (requested_pickup_at, requested_delivery_at),
  KEY idx_orders_company_status (company_id, status),
  KEY idx_orders_currency (currency_id),
  KEY idx_orders_created_by (created_by_user_id),
  CONSTRAINT fk_orders_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_orders_shipper FOREIGN KEY (shipper_party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_orders_receiver FOREIGN KEY (receiver_party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_orders_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id),
  CONSTRAINT fk_orders_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_stops (
  order_stop_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  stop_number SMALLINT UNSIGNED NOT NULL,
  stop_type ENUM('PICKUP','DELIVERY','RETURN','DESTROY','CROSS_DOCK','YARD') NOT NULL,
  party_id BIGINT UNSIGNED NULL,
  party_address_id BIGINT UNSIGNED NULL,
  scheduled_from DATETIME NULL,
  scheduled_to DATETIME NULL,
  actual_arrival_at DATETIME NULL,
  actual_departure_at DATETIME NULL,
  quantity_planned DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  quantity_actual DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('PLANNED','ARRIVED','LOADING','LOADED','UNLOADING','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PLANNED',
  notes VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (order_stop_id),
  UNIQUE KEY uk_order_stops_sequence (order_id, stop_number),
  KEY idx_order_stops_type_status (stop_type, status),
  KEY idx_order_stops_party (party_id),
  KEY idx_order_stops_address (party_address_id),
  CONSTRAINT fk_order_stops_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_order_stops_party FOREIGN KEY (party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_order_stops_address FOREIGN KEY (party_address_id) REFERENCES party_addresses(party_address_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_items (
  order_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  item_description VARCHAR(180) NOT NULL,
  commodity_code VARCHAR(80) NULL,
  package_type VARCHAR(60) NULL,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 1.00,
  weight_lbs DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  length_in DECIMAL(10,2) NULL,
  width_in DECIMAL(10,2) NULL,
  height_in DECIMAL(10,2) NULL,
  hazmat_flag BOOLEAN NOT NULL DEFAULT FALSE,
  temperature_min_f DECIMAL(8,2) NULL,
  temperature_max_f DECIMAL(8,2) NULL,
  status ENUM('ACTIVE','DAMAGED','DESTROYED','RETURNED','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (order_item_id),
  KEY idx_order_items_order (order_id),
  KEY idx_order_items_status (status),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_rates (
  order_rate_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  rate_code VARCHAR(60) NOT NULL,
  description VARCHAR(180) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 1.000,
  unit_rate DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  currency_id BIGINT UNSIGNED NOT NULL,
  bill_to_party_id BIGINT UNSIGNED NOT NULL,
  status ENUM('DRAFT','APPROVED','INVOICED','VOID') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (order_rate_id),
  KEY idx_order_rates_order_status (order_id, status),
  KEY idx_order_rates_bill_to (bill_to_party_id),
  KEY idx_order_rates_currency (currency_id),
  CONSTRAINT fk_order_rates_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_order_rates_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id),
  CONSTRAINT fk_order_rates_bill_to FOREIGN KEY (bill_to_party_id) REFERENCES parties(party_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trips (
  trip_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  trip_number VARCHAR(50) NOT NULL,
  trip_type ENUM('COMPANY_TRUCK','CARRIER') NOT NULL,
  carrier_party_id BIGINT UNSIGNED NULL,
  truck_id BIGINT UNSIGNED NULL,
  origin_terminal_id BIGINT UNSIGNED NULL,
  destination_terminal_id BIGINT UNSIGNED NULL,
  planned_start_at DATETIME NULL,
  planned_end_at DATETIME NULL,
  actual_start_at DATETIME NULL,
  actual_end_at DATETIME NULL,
  total_planned_miles DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_actual_miles DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('DRAFT','PLANNED','DISPATCHED','IN_PROGRESS','ON_HOLD','COMPLETED','CANCELLED','CLOSED') NOT NULL DEFAULT 'DRAFT',
  accounting_status ENUM('NOT_READY','PENDING_REVIEW','VERIFIED','REJECTED','SETTLED') NOT NULL DEFAULT 'NOT_READY',
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trip_id),
  UNIQUE KEY uk_trips_company_number (company_id, trip_number),
  KEY idx_trips_company_status (company_id, status),
  KEY idx_trips_type_carrier (trip_type, carrier_party_id),
  KEY idx_trips_truck (truck_id),
  KEY idx_trips_dates (planned_start_at, planned_end_at),
  CONSTRAINT fk_trips_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_trips_carrier FOREIGN KEY (carrier_party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_trips_truck FOREIGN KEY (truck_id) REFERENCES trucks(truck_id),
  CONSTRAINT fk_trips_origin_terminal FOREIGN KEY (origin_terminal_id) REFERENCES terminals(terminal_id),
  CONSTRAINT fk_trips_destination_terminal FOREIGN KEY (destination_terminal_id) REFERENCES terminals(terminal_id),
  CONSTRAINT fk_trips_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_drivers (
  trip_driver_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trip_id BIGINT UNSIGNED NOT NULL,
  driver_id BIGINT UNSIGNED NOT NULL,
  driver_role ENUM('PRIMARY','TEAM','HELPER','LOCAL_WORKER') NOT NULL DEFAULT 'PRIMARY',
  pay_rate_type ENUM('MILE','HOUR','PERCENTAGE','FLAT') NOT NULL DEFAULT 'MILE',
  pay_rate DECIMAL(12,4) NOT NULL DEFAULT 0.0000,
  status ENUM('ASSIGNED','REMOVED','COMPLETED') NOT NULL DEFAULT 'ASSIGNED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trip_driver_id),
  UNIQUE KEY uk_trip_drivers_driver (trip_id, driver_id, driver_role),
  KEY idx_trip_drivers_driver (driver_id),
  KEY idx_trip_drivers_status (status),
  CONSTRAINT fk_trip_drivers_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_trip_drivers_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_equipment (
  trip_equipment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trip_id BIGINT UNSIGNED NOT NULL,
  equipment_type ENUM('TRUCK','TRAILER','CONTAINER','CHASSIS') NOT NULL,
  truck_id BIGINT UNSIGNED NULL,
  trailer_asset_id BIGINT UNSIGNED NULL,
  attached_at DATETIME NULL,
  detached_at DATETIME NULL,
  status ENUM('ATTACHED','DETACHED','PLANNED','CANCELLED') NOT NULL DEFAULT 'PLANNED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trip_equipment_id),
  KEY idx_trip_equipment_trip_type (trip_id, equipment_type),
  KEY idx_trip_equipment_truck (truck_id),
  KEY idx_trip_equipment_asset (trailer_asset_id),
  KEY idx_trip_equipment_status (status),
  CONSTRAINT fk_trip_equipment_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_trip_equipment_truck FOREIGN KEY (truck_id) REFERENCES trucks(truck_id),
  CONSTRAINT fk_trip_equipment_asset FOREIGN KEY (trailer_asset_id) REFERENCES trailer_assets(trailer_asset_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_events (
  trip_event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trip_id BIGINT UNSIGNED NOT NULL,
  event_order SMALLINT UNSIGNED NOT NULL,
  event_type ENUM('ACQUIRE_TRUCK','HOOK_TRAILER','PICKUP_LOAD','DROP_YARD','DROP_DOCK','DROP_TRAILER','HOOK_CHASSIS','LIFT_ON_CONTAINER','LIFT_OFF_CONTAINER','DROP_CHASSIS','DELIVER_LOAD','RETURN_LOAD','DESTROY_LOAD','CROSS_DOCK','CUSTOM') NOT NULL,
  planner_user_id BIGINT UNSIGNED NULL,
  terminal_id BIGINT UNSIGNED NULL,
  predefined_address_id BIGINT UNSIGNED NULL,
  planned_at DATETIME NULL,
  actual_at DATETIME NULL,
  event_miles DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  expense_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  extra_pay_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  currency_id BIGINT UNSIGNED NOT NULL,
  event_status ENUM('PLANNED','DISPATCHED','ARRIVED','COMPLETED','SKIPPED','FAILED','CANCELLED') NOT NULL DEFAULT 'PLANNED',
  notes VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trip_event_id),
  UNIQUE KEY uk_trip_events_order (trip_id, event_order),
  KEY idx_trip_events_type_status (event_type, event_status),
  KEY idx_trip_events_planner (planner_user_id),
  KEY idx_trip_events_terminal (terminal_id),
  KEY idx_trip_events_address (predefined_address_id),
  KEY idx_trip_events_time (planned_at, actual_at),
  CONSTRAINT fk_trip_events_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_trip_events_planner FOREIGN KEY (planner_user_id) REFERENCES users(user_id),
  CONSTRAINT fk_trip_events_terminal FOREIGN KEY (terminal_id) REFERENCES terminals(terminal_id),
  CONSTRAINT fk_trip_events_address FOREIGN KEY (predefined_address_id) REFERENCES predefined_addresses(predefined_address_id),
  CONSTRAINT fk_trip_events_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_event_orders (
  trip_event_order_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trip_event_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  order_stop_id BIGINT UNSIGNED NULL,
  quantity_handled DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('PLANNED','PARTIAL','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PLANNED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trip_event_order_id),
  UNIQUE KEY uk_trip_event_orders (trip_event_id, order_id, order_stop_id),
  KEY idx_trip_event_orders_order (order_id),
  KEY idx_trip_event_orders_stop (order_stop_id),
  KEY idx_trip_event_orders_status (status),
  CONSTRAINT fk_trip_event_orders_event FOREIGN KEY (trip_event_id) REFERENCES trip_events(trip_event_id),
  CONSTRAINT fk_trip_event_orders_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_trip_event_orders_stop FOREIGN KEY (order_stop_id) REFERENCES order_stops(order_stop_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_expenses (
  trip_expense_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trip_id BIGINT UNSIGNED NOT NULL,
  trip_event_id BIGINT UNSIGNED NULL,
  expense_type ENUM('FUEL','LUMPER','TOLL','PARKING','REPAIR','DETENTION','OTHER') NOT NULL,
  amount DECIMAL(14,2) NOT NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  paid_by ENUM('DRIVER','COMPANY','CARRIER','CUSTOMER') NOT NULL DEFAULT 'COMPANY',
  reimbursable BOOLEAN NOT NULL DEFAULT TRUE,
  verification_status ENUM('PENDING','APPROVED','REJECTED','PAID') NOT NULL DEFAULT 'PENDING',
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trip_expense_id),
  KEY idx_trip_expenses_trip_status (trip_id, verification_status),
  KEY idx_trip_expenses_event (trip_event_id),
  KEY idx_trip_expenses_type (expense_type),
  CONSTRAINT fk_trip_expenses_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_trip_expenses_event FOREIGN KEY (trip_event_id) REFERENCES trip_events(trip_event_id),
  CONSTRAINT fk_trip_expenses_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id),
  CONSTRAINT fk_trip_expenses_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_pti_records (
  trip_pti_record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trip_id BIGINT UNSIGNED NOT NULL,
  equipment_type ENUM('TRUCK','TRAILER','CONTAINER','CHASSIS') NOT NULL,
  equipment_id BIGINT UNSIGNED NOT NULL,
  inspection_at DATETIME NOT NULL,
  inspected_by_user_id BIGINT UNSIGNED NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  document_attachment_id BIGINT UNSIGNED NULL,
  status ENUM('PASSED','FAILED','REPAIR_REQUIRED','VOID') NOT NULL DEFAULT 'PASSED',
  notes VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trip_pti_record_id),
  KEY idx_trip_pti_trip (trip_id),
  KEY idx_trip_pti_equipment (equipment_type, equipment_id),
  KEY idx_trip_pti_user (inspected_by_user_id),
  KEY idx_trip_pti_document (document_attachment_id),
  CONSTRAINT fk_trip_pti_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_trip_pti_user FOREIGN KEY (inspected_by_user_id) REFERENCES users(user_id),
  CONSTRAINT fk_trip_pti_document FOREIGN KEY (document_attachment_id) REFERENCES document_attachments(document_attachment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_account_verifications (
  trip_account_verification_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trip_id BIGINT UNSIGNED NOT NULL,
  verified_by_user_id BIGINT UNSIGNED NULL,
  verified_at DATETIME NULL,
  verification_status ENUM('PENDING','VERIFIED','REJECTED','NEEDS_INFO') NOT NULL DEFAULT 'PENDING',
  notes VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trip_account_verification_id),
  UNIQUE KEY uk_trip_account_verifications_trip (trip_id),
  KEY idx_trip_account_verifications_user (verified_by_user_id),
  KEY idx_trip_account_verifications_status (verification_status),
  CONSTRAINT fk_trip_account_verifications_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_trip_account_verifications_user FOREIGN KEY (verified_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cross_dock_jobs (
  cross_dock_job_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  trip_id BIGINT UNSIGNED NOT NULL,
  trip_event_id BIGINT UNSIGNED NULL,
  terminal_id BIGINT UNSIGNED NOT NULL,
  inbound_order_id BIGINT UNSIGNED NULL,
  outbound_order_id BIGINT UNSIGNED NULL,
  dock_door VARCHAR(40) NULL,
  handling_units DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('PLANNED','IN_PROGRESS','COMPLETED','EXCEPTION','CANCELLED') NOT NULL DEFAULT 'PLANNED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (cross_dock_job_id),
  KEY idx_cross_dock_jobs_trip (trip_id),
  KEY idx_cross_dock_jobs_terminal_status (terminal_id, status),
  KEY idx_cross_dock_jobs_inbound (inbound_order_id),
  KEY idx_cross_dock_jobs_outbound (outbound_order_id),
  CONSTRAINT fk_cross_dock_jobs_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_cross_dock_jobs_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_cross_dock_jobs_event FOREIGN KEY (trip_event_id) REFERENCES trip_events(trip_event_id),
  CONSTRAINT fk_cross_dock_jobs_terminal FOREIGN KEY (terminal_id) REFERENCES terminals(terminal_id),
  CONSTRAINT fk_cross_dock_jobs_inbound FOREIGN KEY (inbound_order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_cross_dock_jobs_outbound FOREIGN KEY (outbound_order_id) REFERENCES orders(order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
  invoice_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  invoice_number VARCHAR(50) NOT NULL,
  customer_party_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  invoice_date DATE NOT NULL,
  due_date DATE NOT NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  subtotal_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('DRAFT','APPROVED','SENT','PARTIAL_PAID','PAID','VOID','OVERDUE') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (invoice_id),
  UNIQUE KEY uk_invoices_company_number (company_id, invoice_number),
  KEY idx_invoices_customer_status (customer_party_id, status),
  KEY idx_invoices_order (order_id),
  KEY idx_invoices_dates (invoice_date, due_date),
  CONSTRAINT fk_invoices_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_invoices_customer FOREIGN KEY (customer_party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_invoices_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_invoices_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_lines (
  invoice_line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_id BIGINT UNSIGNED NOT NULL,
  order_rate_id BIGINT UNSIGNED NULL,
  line_description VARCHAR(180) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 1.000,
  unit_price DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  line_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('ACTIVE','VOID') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (invoice_line_id),
  KEY idx_invoice_lines_invoice (invoice_id),
  KEY idx_invoice_lines_order_rate (order_rate_id),
  CONSTRAINT fk_invoice_lines_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id),
  CONSTRAINT fk_invoice_lines_order_rate FOREIGN KEY (order_rate_id) REFERENCES order_rates(order_rate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bills (
  bill_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  bill_number VARCHAR(50) NOT NULL,
  vendor_party_id BIGINT UNSIGNED NOT NULL,
  trip_id BIGINT UNSIGNED NULL,
  bill_date DATE NOT NULL,
  due_date DATE NOT NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  subtotal_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('DRAFT','APPROVED','PARTIAL_PAID','PAID','VOID','OVERDUE') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (bill_id),
  UNIQUE KEY uk_bills_company_number (company_id, bill_number),
  KEY idx_bills_vendor_status (vendor_party_id, status),
  KEY idx_bills_trip (trip_id),
  KEY idx_bills_dates (bill_date, due_date),
  CONSTRAINT fk_bills_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_bills_vendor FOREIGN KEY (vendor_party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_bills_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_bills_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bill_lines (
  bill_line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  bill_id BIGINT UNSIGNED NOT NULL,
  trip_expense_id BIGINT UNSIGNED NULL,
  line_description VARCHAR(180) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 1.000,
  unit_price DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  line_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('ACTIVE','VOID') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (bill_line_id),
  KEY idx_bill_lines_bill (bill_id),
  KEY idx_bill_lines_trip_expense (trip_expense_id),
  CONSTRAINT fk_bill_lines_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id),
  CONSTRAINT fk_bill_lines_trip_expense FOREIGN KEY (trip_expense_id) REFERENCES trip_expenses(trip_expense_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS statement_runs (
  statement_run_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  statement_number VARCHAR(50) NOT NULL,
  statement_entity_type ENUM('DRIVER','TRUCK','TRAILER','CARRIER','EMPLOYEE','CUSTOMER','SUPPLIER') NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  gross_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  deduction_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('DRAFT','APPROVED','PAID','VOID') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statement_run_id),
  UNIQUE KEY uk_statement_runs_company_number (company_id, statement_number),
  KEY idx_statement_runs_entity_period (statement_entity_type, entity_id, period_start, period_end),
  KEY idx_statement_runs_status (company_id, status),
  CONSTRAINT fk_statement_runs_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_statement_runs_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS statement_lines (
  statement_line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  statement_run_id BIGINT UNSIGNED NOT NULL,
  source_type ENUM('TRIP','EXPENSE','FUEL','ADJUSTMENT','PAYROLL','BILL','INVOICE') NOT NULL,
  source_id BIGINT UNSIGNED NULL,
  line_description VARCHAR(180) NOT NULL,
  amount DECIMAL(14,2) NOT NULL,
  status ENUM('ACTIVE','VOID') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statement_line_id),
  KEY idx_statement_lines_run (statement_run_id),
  KEY idx_statement_lines_source (source_type, source_id),
  CONSTRAINT fk_statement_lines_run FOREIGN KEY (statement_run_id) REFERENCES statement_runs(statement_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlements (
  settlement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  settlement_number VARCHAR(50) NOT NULL,
  payee_type ENUM('DRIVER','CARRIER','EMPLOYEE','SUPPLIER') NOT NULL,
  payee_id BIGINT UNSIGNED NOT NULL,
  statement_run_id BIGINT UNSIGNED NULL,
  settlement_date DATE NOT NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('DRAFT','APPROVED','PAID','VOID') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (settlement_id),
  UNIQUE KEY uk_settlements_company_number (company_id, settlement_number),
  KEY idx_settlements_payee (payee_type, payee_id),
  KEY idx_settlements_statement (statement_run_id),
  KEY idx_settlements_status (company_id, status),
  CONSTRAINT fk_settlements_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_settlements_statement FOREIGN KEY (statement_run_id) REFERENCES statement_runs(statement_run_id),
  CONSTRAINT fk_settlements_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_lines (
  settlement_line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  settlement_id BIGINT UNSIGNED NOT NULL,
  statement_line_id BIGINT UNSIGNED NULL,
  line_description VARCHAR(180) NOT NULL,
  amount DECIMAL(14,2) NOT NULL,
  status ENUM('ACTIVE','VOID') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (settlement_line_id),
  KEY idx_settlement_lines_settlement (settlement_id),
  KEY idx_settlement_lines_statement_line (statement_line_id),
  CONSTRAINT fk_settlement_lines_settlement FOREIGN KEY (settlement_id) REFERENCES settlements(settlement_id),
  CONSTRAINT fk_settlement_lines_statement_line FOREIGN KEY (statement_line_id) REFERENCES statement_lines(statement_line_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS claims (
  claim_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  claim_number VARCHAR(50) NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  trip_id BIGINT UNSIGNED NULL,
  claimant_party_id BIGINT UNSIGNED NULL,
  claim_type ENUM('DAMAGE','SHORTAGE','ACCIDENT','LATE_DELIVERY','THEFT','OTHER') NOT NULL,
  claim_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  currency_id BIGINT UNSIGNED NOT NULL,
  incident_date DATE NULL,
  status ENUM('OPEN','INVESTIGATING','APPROVED','DENIED','SETTLED','CLOSED') NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (claim_id),
  UNIQUE KEY uk_claims_company_number (company_id, claim_number),
  KEY idx_claims_order (order_id),
  KEY idx_claims_trip (trip_id),
  KEY idx_claims_status (company_id, status),
  CONSTRAINT fk_claims_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_claims_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_claims_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id),
  CONSTRAINT fk_claims_claimant FOREIGN KEY (claimant_party_id) REFERENCES parties(party_id),
  CONSTRAINT fk_claims_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS claim_events (
  claim_event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  claim_id BIGINT UNSIGNED NOT NULL,
  event_type ENUM('CREATED','NOTE','DOCUMENT_ADDED','STATUS_CHANGED','PAYMENT','CLOSED') NOT NULL,
  event_note VARCHAR(500) NULL,
  event_by_user_id BIGINT UNSIGNED NULL,
  event_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('ACTIVE','VOID') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (claim_event_id),
  KEY idx_claim_events_claim_time (claim_id, event_at),
  KEY idx_claim_events_user (event_by_user_id),
  CONSTRAINT fk_claim_events_claim FOREIGN KEY (claim_id) REFERENCES claims(claim_id),
  CONSTRAINT fk_claim_events_user FOREIGN KEY (event_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_categories (
  inventory_category_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  category_code VARCHAR(40) NOT NULL,
  category_name VARCHAR(120) NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (inventory_category_id),
  UNIQUE KEY uk_inventory_categories_company_code (company_id, category_code),
  KEY idx_inventory_categories_status (status),
  CONSTRAINT fk_inventory_categories_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_items (
  inventory_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  inventory_category_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(60) NOT NULL,
  item_name VARCHAR(160) NOT NULL,
  unit_of_measure VARCHAR(20) NOT NULL DEFAULT 'EA',
  reorder_level DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('ACTIVE','INACTIVE','DISCONTINUED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (inventory_item_id),
  UNIQUE KEY uk_inventory_items_company_sku (company_id, sku),
  KEY idx_inventory_items_category (inventory_category_id),
  KEY idx_inventory_items_status (status),
  CONSTRAINT fk_inventory_items_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_inventory_items_category FOREIGN KEY (inventory_category_id) REFERENCES inventory_categories(inventory_category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_locations (
  inventory_location_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  warehouse_id BIGINT UNSIGNED NOT NULL,
  location_code VARCHAR(60) NOT NULL,
  location_name VARCHAR(120) NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (inventory_location_id),
  UNIQUE KEY uk_inventory_locations_warehouse_code (warehouse_id, location_code),
  KEY idx_inventory_locations_company_status (company_id, status),
  CONSTRAINT fk_inventory_locations_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_inventory_locations_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(warehouse_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_stock_movements (
  stock_movement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  inventory_item_id BIGINT UNSIGNED NOT NULL,
  inventory_location_id BIGINT UNSIGNED NOT NULL,
  movement_type ENUM('RECEIPT','ISSUE','TRANSFER','ADJUSTMENT','RETURN') NOT NULL,
  quantity DECIMAL(12,2) NOT NULL,
  unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  reference_type ENUM('MANUAL','TRUCK','TRAILER','CHASSIS','DRIVER','ORDER','TRIP') NOT NULL DEFAULT 'MANUAL',
  reference_id BIGINT UNSIGNED NULL,
  moved_by_user_id BIGINT UNSIGNED NULL,
  moved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('POSTED','VOID','PENDING') NOT NULL DEFAULT 'POSTED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (stock_movement_id),
  KEY idx_stock_movements_item_location (inventory_item_id, inventory_location_id),
  KEY idx_stock_movements_reference (reference_type, reference_id),
  KEY idx_stock_movements_date (moved_at),
  KEY idx_stock_movements_status (company_id, status),
  CONSTRAINT fk_stock_movements_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_stock_movements_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(inventory_item_id),
  CONSTRAINT fk_stock_movements_location FOREIGN KEY (inventory_location_id) REFERENCES inventory_locations(inventory_location_id),
  CONSTRAINT fk_stock_movements_user FOREIGN KEY (moved_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS equipment_item_assignments (
  equipment_item_assignment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  inventory_item_id BIGINT UNSIGNED NOT NULL,
  assigned_entity_type ENUM('TRUCK','TRAILER','CHASSIS','CONTAINER','DRIVER') NOT NULL,
  assigned_entity_id BIGINT UNSIGNED NOT NULL,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 1.00,
  assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  returned_at DATETIME NULL,
  status ENUM('ASSIGNED','RETURNED','LOST','DAMAGED') NOT NULL DEFAULT 'ASSIGNED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (equipment_item_assignment_id),
  KEY idx_equipment_item_assignments_entity (assigned_entity_type, assigned_entity_id),
  KEY idx_equipment_item_assignments_item (inventory_item_id),
  KEY idx_equipment_item_assignments_status (company_id, status),
  CONSTRAINT fk_equipment_item_assignments_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_equipment_item_assignments_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(inventory_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_leave_types (
  leave_type_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  leave_code VARCHAR(40) NOT NULL,
  leave_name VARCHAR(120) NOT NULL,
  annual_days DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  paid_flag BOOLEAN NOT NULL DEFAULT TRUE,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (leave_type_id),
  UNIQUE KEY uk_hr_leave_types_company_code (company_id, leave_code),
  KEY idx_hr_leave_types_status (status),
  CONSTRAINT fk_hr_leave_types_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_leave_requests (
  leave_request_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  employee_id BIGINT UNSIGNED NOT NULL,
  leave_type_id BIGINT UNSIGNED NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_days DECIMAL(8,2) NOT NULL,
  reason VARCHAR(500) NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  status ENUM('REQUESTED','APPROVED','REJECTED','CANCELLED','TAKEN') NOT NULL DEFAULT 'REQUESTED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (leave_request_id),
  KEY idx_leave_requests_employee_dates (employee_id, start_date, end_date),
  KEY idx_leave_requests_type (leave_type_id),
  KEY idx_leave_requests_status (company_id, status),
  CONSTRAINT fk_leave_requests_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id),
  CONSTRAINT fk_leave_requests_type FOREIGN KEY (leave_type_id) REFERENCES hr_leave_types(leave_type_id),
  CONSTRAINT fk_leave_requests_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_logs (
  attendance_log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  employee_id BIGINT UNSIGNED NOT NULL,
  work_date DATE NOT NULL,
  clock_in_at DATETIME NULL,
  clock_out_at DATETIME NULL,
  total_hours DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  source ENUM('WEB','MOBILE','IMPORT','MANUAL') NOT NULL DEFAULT 'WEB',
  status ENUM('OPEN','APPROVED','REJECTED','ADJUSTED') NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (attendance_log_id),
  UNIQUE KEY uk_attendance_logs_employee_date (employee_id, work_date),
  KEY idx_attendance_logs_company_status (company_id, status),
  CONSTRAINT fk_attendance_logs_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_attendance_logs_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payroll_runs (
  payroll_run_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  payroll_number VARCHAR(50) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  pay_date DATE NOT NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  gross_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  deduction_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('DRAFT','APPROVED','PAID','VOID') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (payroll_run_id),
  UNIQUE KEY uk_payroll_runs_company_number (company_id, payroll_number),
  KEY idx_payroll_runs_period (period_start, period_end),
  KEY idx_payroll_runs_status (company_id, status),
  CONSTRAINT fk_payroll_runs_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_payroll_runs_currency FOREIGN KEY (currency_id) REFERENCES currencies(currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payroll_lines (
  payroll_line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payroll_run_id BIGINT UNSIGNED NOT NULL,
  employee_id BIGINT UNSIGNED NOT NULL,
  gross_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  deduction_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('ACTIVE','VOID') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (payroll_line_id),
  UNIQUE KEY uk_payroll_lines_run_employee (payroll_run_id, employee_id),
  KEY idx_payroll_lines_employee (employee_id),
  CONSTRAINT fk_payroll_lines_run FOREIGN KEY (payroll_run_id) REFERENCES payroll_runs(payroll_run_id),
  CONSTRAINT fk_payroll_lines_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS api_integrations (
  api_integration_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  integration_code VARCHAR(60) NOT NULL,
  integration_name VARCHAR(140) NOT NULL,
  provider_type ENUM('CURRENCY_RATE','FUEL_BDE','GPS','ELD','ACCOUNTING','OTHER') NOT NULL,
  base_url VARCHAR(255) NULL,
  credential_reference VARCHAR(255) NULL,
  sync_frequency_minutes INT UNSIGNED NOT NULL DEFAULT 1440,
  last_sync_at DATETIME NULL,
  status ENUM('ACTIVE','PAUSED','ERROR','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (api_integration_id),
  UNIQUE KEY uk_api_integrations_company_code (company_id, integration_code),
  KEY idx_api_integrations_provider_status (provider_type, status),
  CONSTRAINT fk_api_integrations_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS integration_sync_logs (
  integration_sync_log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  api_integration_id BIGINT UNSIGNED NOT NULL,
  sync_started_at DATETIME NOT NULL,
  sync_finished_at DATETIME NULL,
  status ENUM('STARTED','SUCCESS','FAILED','PARTIAL') NOT NULL DEFAULT 'STARTED',
  records_read INT UNSIGNED NOT NULL DEFAULT 0,
  records_inserted INT UNSIGNED NOT NULL DEFAULT 0,
  records_updated INT UNSIGNED NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (integration_sync_log_id),
  KEY idx_integration_sync_logs_integration_time (api_integration_id, sync_started_at),
  KEY idx_integration_sync_logs_status (status),
  CONSTRAINT fk_integration_sync_logs_integration FOREIGN KEY (api_integration_id) REFERENCES api_integrations(api_integration_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
  audit_log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id BIGINT UNSIGNED NULL,
  action_name VARCHAR(80) NOT NULL,
  old_values JSON NULL,
  new_values JSON NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  status ENUM('SUCCESS','FAILED') NOT NULL DEFAULT 'SUCCESS',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (audit_log_id),
  KEY idx_audit_logs_company_time (company_id, created_at),
  KEY idx_audit_logs_user_time (user_id, created_at),
  KEY idx_audit_logs_entity (entity_type, entity_id),
  KEY idx_audit_logs_action (action_name),
  CONSTRAINT fk_audit_logs_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
  CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
